#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server:
# Requirements:
#   Accepts 4 parameters
#     The path to the file to be transferred
#     The IP of the server we want to transfer the file to
#     The username scp connects with
#     The path to the SSH private key that scp uses
# Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
# scp transfer the file to the user home directory ~/
# Strict host key checking be disabled when using scp
if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	# Define variables
	PATH_FILE=$1
	IP=$2
	UNAME=$3
	PATH_SSH_KEY=$4
	scp -i "$PATH_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_FILE" "$UNAME@$IP:~/"
fi