#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update
sudo apt-get -y install nginx
# Able port 80
sudo ufw allow 'Nginx HTTP'
# Add line in server block
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://youtu.be/l9_-2oG4Cc0 permanent;" /etc/nginx/sites-available/default
# Restart nginx to load changes
sudo service nginx restart
