#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Requirements:
#    Configure HAproxy with version equal or greater than 1.5 so that it send traffic to web-01 and web-02
#    Distribute requests using a roundrobin algorithm
#    Make sure that HAproxy is managed via an init script
# Install haproxy
sudo apt-get -y update
sudo apt-get -y install haproxy

# CONFIGURATION LOAD BALANCER
#   enable HAProxy to be started by the init script
sudo echo "ENABLE=1" >> /etc/default/haproxy

echo -e "\n******************* Preparing HAproxy init *********************\n"
sleep 2
#   Change is done properly execute the init script of HAProxy
#   sudo etc/init.d/haproxy start

echo "Add new configuration to haproxy"
#   Add new configuration to haproxy
sudo echo "

frontend http
  bind *:80
  mode http
  default_backend http_back

backend http_back
   balance roundrobin
   server 1460-web-01-1596432388 34.73.138.116:80 check
   server 1460-web-02 54.145.53.228:80 check
" >> /etc/haproxy/haproxy.cfg

# start the HAProxy service
service haproxy restart
