#!/usr/bin/bash
#script that generates a MySQL dump and creates a compressed archive out of it.
# Requirements:
# The MySQL dump all your MySQL databases
# The MySQL dump is named backup.sql
# The MySQL dump file is compressed to a tar.gz archive
# This archive have the following name format: day-month-year.tar.gz
# The user to connect to the MySQL database is root
mysqldump -u root -p"$1" --all-databases > backup.sql
DATE=$(date +%d-%m-%Y)
tar -czvf "$DATE.tar.gz" backup.sql
