#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/holbertonscript.pid containing its PID
#     Displays To infinity and beyond indefinitely
#     Displays I hate the kill command when receiving a SIGTERM signal
#     Displays Y U no love me?! when receiving a SIGINT signal
#     Deletes the file /var/run/holbertonscript.pid and terminates itself
#       when receiving a SIGQUIT or SIGTERM signal
fi_created=/var/run/holbertonscript.pid
echo $$ > "$fi_created"
while (( 1 ))
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'rm $fi_created; exit' SIGQUIT # first read QUIT, later TERM
    trap 'echo "I hate the kill command"; rm $fi_created; exit' SIGTERM
done
