#!/usr/bin/env bash
# Bash script that kills the process 7-highlander
# By default, it's the SIGTERM signal that gets sent, but if you want,
# we change the signal using the --signal command-line option
# --signal SIGTERM
pkill --signal 9 -f 7-highlander
