#!/usr/bin/env bash
# Bash script that groups visitors by IP and HTTP status code, and
# displays this data.
# The exact format must be:
# OCCURENCE_NUMBER - IP - HTTP_CODE. In list format
# Same: cat apache-access.log | awk '{print $1,$9}'
awk '{print $1,$9}' < apache-access.log | sort | uniq -c | sort -nr
