#!/usr/bin/env bash
# That displays Holberton School 10 times, 9th iteration displays too "Hi"
counter=1
while [ $counter -le 10 ]
do
    echo "Holberton School"
    if [ "$counter" -eq 9 ]
    then
	echo "Hi"
    fi
    counter=$(( counter + 1 ))
done
