#!/usr/bin/env bash
# bad luck for the 4th loop iteration, good luck for the 8th loop iteration
# Holberton School for the other iterations
counter=1
ms4="bad luck from China"
ms9="bad luck from Japan"
ms17="bad luck from Italy"
while [ $counter -le 20 ]
do
    echo $counter
    case "${counter}"
    in
	4) echo "$ms4";;
	9) echo "$ms9";;
	17) echo "$ms17";;
    esac
    counter=$(( counter + 1 ))
done
