#!/usr/bin/env bash
# Bash script that gives you information about the holbertonschool file
# Bash script should check if the file exists and print:
# if the file exists: holbertonschool file exists
# if the file does not exist: holbertonschool file does not exist
# If the file exists, print:
# if the file is empty: holbertonschool file is empty
# if the file is not empty: holbertonschool file is not empty
# if the file is a regular file: holbertonschool is a regular file
# if the file is not a regular file: (nothing)
file="holbertonschool"
if [ -e "$file" ]
then
        echo "$file file exists"
	if ! [ -s "$file" ]
	then
	    echo "holbertonschool file is empty"
	else
	    echo "holbertonschool file is not empty"
	fi # end empty
	if [ -f "$file" ]
	    then
	    echo "holbertonschool is a regular file"
	fi # end regular
else
    echo "holbertonschool file does not exist"
fi # end script
