#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine its executed on
# You can use 'inet addr:K\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
ifconfig | grep -Po '(?<=inet addr:)(\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})'
