#!/usr/bin/env bash
# script that configures the container so that Nginx is running as the nginx user. 7 lines long or less
pkill apache2
sudo sed -i "s/www-data/nginx/g" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
service nginx restart
