#!/usr/bin/env bash
# Bash script that creates an RSA key pair
#    Name of the created private key be holberton
#    Number of bits 4096
#    The created key protected by the passphrase betty
ssh-keygen -b 4096 -N betty -f holberton
